#!/bin/sh
### BEGIN INIT INFO
# Provides:          homebridge
# Required-Start:    $remote_fs dbus garage-door-gpio
# Required-Stop:     $remote_fs dbus
# Should-Start:	     $syslog
# Should-Stop:       $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts HomeBridge
# Description:       Starts HomeBridge
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="Starts up HomeBridge (HomeKit Bridge)"
NAME="homebridge"
SCRIPTNAME=/etc/init.d/$NAME

. /lib/lsb/init-functions

case "$1" in
    start)
        log_daemon_msg "Starting $NAME"

	/usr/local/bin/homebridge -U /home/pi/.homebridge 2>&1 | /usr/sbin/rotatelogs /home/pi/.homebridge/homebridge.log.%y%m%d.%s 250M &
 
        log_end_msg $?
        ;;
    stop)
	log_daemon_msg "Stopping $NAME"
        pkill homebridge
        log_end_Msg $?
        ;;
    *)
        echo "Usage: $SCRIPTNAME {start}" >&2
        exit 1
        ;;
esac

exit 0
